[PAXWEB-1058] - Export org.apache.tomcat
Prevent NoClassDefFoundError caused by org/apache/tomcat/InstanceManager

https://ops4j1.jira.com/browse/PAXWEB-1058

(cherry picked from commit faea127)
Signed-off-by: anierbeck <bcanhome@googlemail.com>